# Generated by Django 4.1.13 on 2024-09-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ipAddress',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
    ]
