# Generated by Django 4.1.13 on 2024-09-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_review_ipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ipCount',
            field=models.IntegerField(default=0),
        ),
    ]
