# Generated by Django 4.1.13 on 2024-09-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_review_ipcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ipCount',
            field=models.IntegerField(default=1),
        ),
    ]
