# Generated by Django 4.1.13 on 2024-09-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_review_ipcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='isFake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='polarity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='review',
            name='subjectivity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
