# Generated by Django 4.1.13 on 2024-09-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_review_isfake_review_isverified_review_polarity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAdmin', models.BooleanField(default=False)),
                ('user_name', models.CharField(max_length=255)),
            ],
        ),
    ]
