# Generated by Django 4.1.13 on 2024-09-28 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_isadmin_shop_session_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_session',
            name='is_superuser',
        ),
    ]
